### PR TITLE
Indigo devel diffdrive enhanced

### PR DESCRIPTION
**Pull request by maxbader**
Hi

I enhanced the ros_diff_drive to support a trip recorder and to deliver the current executed command, which can differ to the target command because of the robots acceleration limits.
This values are normally also available on real robot.
- All additional topics are only published if there is a subscriber.
- Topics names can be modified
- The new features can be tested using "roslaunch gazebo_plugins multi_robot_scenario.launch"

Greetings
Markus

Please ignore the changes on: gazebo_ros/src/gazebo_ros_api_plugin.cpp ->There is a separate pull request for that #273

### CODE REVIEW

**Comment by hsu** [comment]
minor comment... can we keep the indent style so the diff is smaller?

**Comment by maxbader** [comment]
I fixed the style, 

@hsu 
The coding style for the gazebo_ros_diff_drive is very messed up. 
I would like to fix the style if possible after a merge

**Comment by maxbader** [comment]
The changes on the GetModelState service are removed but available in jade-devel-GetModelState or indigo-devel-GetModelState related to the pull request #259 and #302

**Comment by scpeters** [comment]
Can you resolve these conflicts?

**Pull request closed without merging**
