### PR TITLE
gazebo_ros_wheel_slip plugin (Noetic)

### PR DESCRIPTION
**Pull request by scpeters**
Uses dynamic_reconfigure to set wheel slip parameters. Forward port of #995.

### CODE REVIEW

**Review by jacobperron — APPROVED** [review]
LGTM

I'm not sure what our CI procedure is for Noetic. I guess this package still needs to be released into Noetic for automatic PR jobs to trigger.

**Comment by chapulina** [comment]
> this package still needs to be released into Noetic for automatic PR jobs to trigger.

We're currently [blocked](http://repositories.ros.org/status_page/blocked_releases_noetic.html?q=id%3D%22gazebo_ros_pkgs%22&s=6&r=1) by `ros_control`. And #1069 is probably necessary.

> I'm not sure what our CI procedure is for Noetic

I think we could add CI for Noetic on https://build.osrfoundation.org using `ros-testing` and ignoring `gazebo_ros_control` for now.

**Comment by scpeters** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
I haven't reviewed, but will merge since it has an approval.

**Pull request merged**
