### PR TITLE
[noetic] Adapted to OpenCV4

### PR DESCRIPTION
**Pull request by ahcorde**
Modified headers for OpenCV4

Signed-off-by: ahcorde <ahcorde@gmail.com>

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
I haven't tried it, but we have positive feedback from the community, so merging.

**Comment by timonegk** [comment]
Could this be backported to melodic? The new header style has been introduced in [OpenCV2.4.11](https://docs.opencv.org/master/db/dfa/tutorial_transition_guide.html#tutorial_transition_hints_24), so that would introduce no problems for melodic (target cv version is 3.2+, see [REP 3](https://www.ros.org/reps/rep-0003.html#melodic-morenia-may-2018-may-2023)) but makes it possible to use melodic with cv4.

**Comment by chapulina** [comment]
@timonegk , sure, please feel free to open a pull request against melodic and we can merge it if CI passes. Thanks!

**Comment by timonegk** [comment]
Okay, I opened a PR, thank you!

**Pull request merged**
