### PR TITLE
launch gazebo directly wo/ launchfile

### PR DESCRIPTION
**Pull request by Karsten1987**
Signed-off-by: Karsten Knese <karsten@openrobotics.org>

CI: [Build Status](https://ci.ros2.org/job/ci_linux/9153/)

### CODE REVIEW

**Comment by Karsten1987** [comment]
This might fix the build errors we see in #1036 
If it turns out green, I'll cherry-pick this commit on top of the existing backport PR

**Comment by Karsten1987** [comment]
Doesn’t seem to have helped much. 

@hidmic is there a way to enforce that all processes of the launchfile are terminated correctly? For context: the launch testfile we have for gazebo doesn’t fully close gazebo so that all follow up tests fail with an already existing gazebo instance running.

**Comment by chapulina** [comment]
There may be something else going on here though, there are tests failing on `gazebo_ros` even before the entity spawner:

```
17:22:11 The following tests FAILED:
17:22:11 	 10 - test_gazebo_ros_factory (Failed)
17:22:11 	 11 - test_gazebo_ros_init (Failed)
17:22:11 	 12 - test_gazebo_ros_joint_effort (Failed)
17:22:11 	 13 - test_gazebo_ros_link_wrench (Failed)
17:22:11 	 14 - test_gazebo_ros_state (Failed)
17:22:11 	 15 - test_node (Failed)
17:22:11 	 16 - test_plugins (Failed)
17:22:11 	 17 - test_sim_time (Failed)
17:22:11 	 19 - test_entity_spawner.test.py (Failed)
17:22:11 Errors while running CTest
```

The failures are not very informative though:

```
17:21:06 test 10
17:21:06       Start 10: test_gazebo_ros_factory
17:21:06 
17:21:06 10: Test command: /home/jenkins-agent/workspace/ci_linux/venv/bin/python3 "-u" "/home/jenkins-agent/workspace/ci_linux/ws/install/ament_cmake_test/share/ament_cmake_test/cmake/run_test.py" "/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test_results/gazebo_ros/test_gazebo_ros_factory.gtest.xml" "--package-name" "gazebo_ros" "--output-file" "/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/ament_cmake_gtest/test_gazebo_ros_factory.txt" "--command" "/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test/test_gazebo_ros_factory" "--gtest_output=xml:/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test_results/gazebo_ros/test_gazebo_ros_factory.gtest.xml"
17:21:06 10: Test timeout computed to be: 120
17:21:07 10: -- run_test.py: invoking following command in '/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test':
17:21:07 10:  - /home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test/test_gazebo_ros_factory --gtest_output=xml:/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test_results/gazebo_ros/test_gazebo_ros_factory.gtest.xml
17:21:07 10: [==========] Running 1 test from 1 test case.
17:21:07 10: [----------] Global test environment set-up.
17:21:07 10: [----------] 1 test from GazeboRosFactoryTest
17:21:07 10: [ RUN      ] GazeboRosFactoryTest.SpawnDelete
17:21:07 10: Gazebo multi-robot simulator, version 9.11.0
17:21:07 10: Copyright (C) 2012 Open Source Robotics Foundation.
17:21:07 10: Released under the Apache 2 License.
17:21:07 10: http://gazebosim.org
17:21:07 10: 
17:21:08 10: -- run_test.py: return code -11
17:21:08 10: -- run_test.py: generate result file '/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test_results/gazebo_ros/test_gazebo_ros_factory.gtest.xml' with failed test
17:21:08 10: -- run_test.py: verify result file '/home/jenkins-agent/workspace/ci_linux/ws/build/gazebo_ros/test_results/gazebo_ros/test_gazebo_ros_factory.gtest.xml'
17:21:08 10/19 Test #10: test_gazebo_ros_factory ..........***Failed    1.30 sec
```

**Comment by Karsten1987** [comment]
return code `-11` most likely indicates a segmentation fault. 

I can't personally reproduce this on my OSX machine. All tests pass for me.

**Comment by hidmic** [comment]
> is there a way to enforce that all processes of the launchfile are terminated correctly?

That's a `launch` concern, and it should be the case that all processes are terminated. It should progressively escalate SIGINT to SIGTERM to SIGKILL. 

Looking at CI output though it'd appear that's not the problem. You're getting segfaults at the very beginning of each test. Does it happen to you locally in Linux? Having a backtrace would be ideal.

**Comment by chapulina** [comment]
@hidmic , I think that the failure on #1033 illustrates better the issue with launch not terminating gzserver.

**Comment by Karsten1987** [comment]
> Does it happen to you locally in Linux? Having a backtrace would be ideal.

I tried this on my OSX host, a Linux VM and a Linux VM tty wo/ X support and haven't had a single test failure. I am unable to reproduce this and honestly a bit puzzled on how to proceed further.

**Comment by hidmic** [comment]
I can't speak for those segfaults, less so if you can't reproduce them. You can give a bit more time to Gazebo to shut down, but that's not necessarily related.

**Comment by chapulina** [comment]
Will forward-port the similar fix that went into #1036

**Pull request closed without merging**
