### PR TITLE
Use proper boolean value for latched in CameraUtils

### PR DESCRIPTION
**Pull request by j-rivero**
Fix for #212. Thanks to Daniel Pinyol.

### CODE REVIEW

**Comment by scpeters** [comment]
So you set the value to `true`, which means latching is enabled? Is that preferred for this topic?

**Comment by scpeters** [comment]
I'm not sure this issue is valid (see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/212#issuecomment-215195235 and https://github.com/ros-simulation/gazebo_ros_pkgs/issues/212#issuecomment-215196026 )

**Comment by j-rivero** [comment]
> So you set the value to true, which means latching is enabled? Is that preferred for this topic?

I was trying to preserve the current behaviour but fix the problem with the API call which evaluates to true.

> I'm not sure this issue is valid (see #212 (comment) and #212 (comment) )

Clearly not valid, thanks.

**Comment by scpeters** [comment]
+1

**Comment by scpeters** [comment]
thanks for the explanation

**Pull request merged**
