### PR TITLE
Fix STL iterator errors, misc. cppcheck (#182)

### LINKED ISSUE #182: Fix errors/warnings detected by the cppcheck in atlas_msgs package.
[Apply patch by anonymous](https://bitbucket.org/osrf/drcsim/issue/162/fix-errors-warnings-detected-by-the)

### PR DESCRIPTION
**Pull request by scpeters**
There were some errors in STL iterators.
Initialized values of member variables in constructor.
Removed an unused variable (model_name).
Use prefix ++.
Fixes #182.

### CODE REVIEW

**Comment by scpeters** [comment]
@adolfo-rt I think you initially submitted the patch to drcsim that this pr is based on (see #182 and [drcsim issue 162](https://bitbucket.org/osrf/drcsim/issue/162/fix-errors-warnings-detected-by-the)).

**Comment by adolfo-rt** [comment]
> @adolfo-rt I think you initially submitted the patch to drcsim that this pr is based on (see #182 and drcsim issue 162).

It's likely, yes. I remember submitting a fix once as _Anonymous_ by mistake. Is there an issue with the proposed fixes?.

**Comment by scpeters** [comment]
That patch was submitted to drcsim when drcsim had a fork of some of the gazebo_plugins. This pull request brings those fixes to gazebo_plugins.

EDIT: No, there's no issues, just waiting for normal code review.

**Comment by hsu** [comment]
looks good.

**Pull request merged**
