### PR TITLE
Update gazebo_ros_planar_move

### PR DESCRIPTION
**Pull request by k-okada**
this may solves #121 and added linear/accel limit
as normal robot platform, it stops the robot if the cmd_vel did not
come for several seconds.

the default behavior is not changed.

gazebo_ros_planar_move: if cmd_vel does not come to joint_state_idel_sec, it stops the robot
gazebo_ros_planar_move : add velocity and acceleration limit
add recovery motion gazebo_ros_planar_move

### CODE REVIEW

**Comment by hsu** [comment]
+1

this PR is a little more complex, I need one more approval or an example / test scenario added to the PR. Thanks!

**Comment by 130s** [comment]
+1

With this I confirm (using a private project) the issue #121 is worked around much better.

(Minimum correction: Title of the PR should be `planar`, not planner.)

**Comment by k-okada** [comment]
thanks for support, I have added test world file `https://github.com/k-okada/gazebo_ros_pkgs/blob/505ee9d637bab272c00cc43994a6df0a83135a4d/gazebo_plugins/test/test_worlds/gazebo_ros_planar_move.world`; you can try with starting following two launch programs;

```
roslaunch gazebo_ros empty_world.launch world_name:=`pwd`/gazebo_ros_planar_move.world 
rosrun teleop_twist_keyboard teleop_twist_keyboard.py
```

**Comment by k-okada** [comment]
by the way, this sometimes segfaults as follow, does any one know how to fix this?

```
 received cmd_vel for 3.000000 sec
[ WARN] [1456059682.698144269, 210.393000000]: PlanarMovePlugin (ns = /) did not received cmd_vel for 3.000000 sec
[ WARN] [1456059688.533006744, 215.393000000]: PlanarMovePlugin (ns = /) did not received cmd_vel for 3.000000 sec
[ WARN] [1456059694.327425110, 220.394000000]: PlanarMovePlugin (ns = /) did not received cmd_vel for 3.000000 sec
[ WARN] [1456059700.108931948, 225.394000000]: PlanarMovePlugin (ns = /) did not received cmd_vel for 3.000000 sec
[ WARN] [1456059705.944673845, 230.393000000]: PlanarMovePlugin (ns = /) did not received cmd_vel for 3.000000 sec
[ WARN] [1456059711.848695174, 235.394000000]: PlanarMovePlugin (ns = /) did not received cmd_vel for 3.000000 sec
pure virtual method called
terminate called without an active exception

Program received signal SIGABRT, Aborted.
[Switching to Thread 0x7fff9a7c3700 (LWP 7667)]
0x00007ffff4ec2cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
56      ../nptl/sysdeps/unix/sysv/linux/raise.c: No such file or directory.
(gdb) where
#0  0x00007ffff4ec2cc9 in __GI_raise (sig=sig@entry=6)
    at ../nptl/sysdeps/unix/sysv/linux/raise.c:56
#1  0x00007ffff4ec60d8 in __GI_abort () at abort.c:89
#2  0x00007ffff54c7535 in __gnu_cxx::__verbose_terminate_handler() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#3  0x00007ffff54c56d6 in ?? () from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#4  0x00007ffff54c5703 in std::terminate() ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#5  0x00007ffff54c61bf in __cxa_pure_virtual ()
   from /usr/lib/x86_64-linux-gnu/libstdc++.so.6
#6  0x00007fffec9f4b20 in dxHashSpace::cleanGeoms() ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_ode.so.2
#7  0x00007fffec9f4981 in dxHashSpace::collide2(void*, dxGeom*, void (*)(void*, dxGeom*, dxGeom*)) () from /usr/lib/x86_64-linux-gnu/libgazebo_ode.so.2
#8  0x00007fffec9f4f77 in dSpaceCollide2 ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_ode.so.2
#9  0x00007ffff2514f90 in gazebo::physics::ODEMultiRayShape::UpdateRays() ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_physics_ode.so.2
#10 0x00007ffff7379f75 in gazebo::physics::MultiRayShape::Update() ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_physics.so.2
#11 0x00007ffff702f2ca in gazebo::sensors::RaySensor::UpdateImpl(bool) ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_sensors.so.2
#12 0x00007ffff70333c4 in gazebo::sensors::Sensor::Update(bool) ()
   from /usr/lib/x86_64-linux-gnu/libgazebo_sensors.so.2
#13 0x00007ffff7039358 in gazebo::sensors::SensorManager::SensorContainer::Update(bool) () from /usr/lib/x86_64-linux-gnu/libgazebo_sensors.so.2
#14 0x00007ffff703b32b in gazebo::sensors::SensorManager::SensorContainer::RunLoop() () from /usr/lib/x86_64-linux-gnu/libgazebo_sensors.so.2
#15 0x00007ffff5be8a4a in ?? ()
   from /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.54.0
#16 0x00007ffff6a1b182 in start_thread (arg=0x7fff9a7c3700)
    at pthread_create.c:312
#17 0x00007ffff4f8647d in clone ()
    at ../sysdeps/unix/sysv/linux/x86_64/clone.S:111
(gdb) info threads
  Id   Target Id         Frame 
  47   Thread 0x7fff3a3c1700 (LWP 7892) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  46   Thread 0x7fff3b25e700 (LWP 7829) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  45   Thread 0x7fff3ba5f700 (LWP 7824) "gzserver" pthread_cond_wait@@GLIBC_2.3.2 () at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_wait.S:185
  43   Thread 0x7fff3ccfb700 (LWP 7820) "gzserver" 0x00007ffff4f7912d in poll
    () at ../sysdeps/unix/syscall-template.S:81
  42   Thread 0x7fff3d948700 (LWP 7814) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  41   Thread 0x7fff50ff9700 (LWP 7788) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  39   Thread 0x7fff51ffb700 (LWP 7776) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  37   Thread 0x7fff52ffd700 (LWP 7771) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  35   Thread 0x7fff53fff700 (LWP 7767) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  33   Thread 0x7fff615a3700 (LWP 7763) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_cond_timedwait.S:238
  31   Thread 0x7fff625a5700 (LWP 7759) "gzserver" pthread_cond_timedwait@@GLIBC_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  28   Thread 0x7fff6aee2700 (LWP 7735) "gzserver" pthreond_wait.S:185
  26   Thread 0x7fff98fc0700 (LWP 7670) "gzserver" pthreond_wait.S:185
  25   Thread 0x7fff997c1700 (LWP 7669) "gzserver" __lll
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevello
  24   Thread 0x7fff99fc2700 (LWP 7668) "gzserver" pthreond_wait.S:185
* 23   Thread 0x7fff9a7c3700 (LWP 7667) "gzserver" 0x000/raise.c:56
  22   Thread 0x7fff9abc4700 (LWP 7612) "gzserver" sysca
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  21   Thread 0x7fff9afc5700 (LWP 7611) "gzserver" sysca
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
---Type <return> to continue, or q <return> to quit---
  20   Thread 0x7fff9b3c6700 (LWP 7610) "gzserver" sysca
    at ../sysdeps/unix/sysv/linux/x86_64/syscall.S:38
  19   Thread 0x7fff9bfff700 (LWP 7608) "gzserver" pthreond_wait.S:185
  18   Thread 0x7fffb8c2d700 (LWP 7607) "gzserver" pthreond_wait.S:185
  17   Thread 0x7fffb942e700 (LWP 7606) "gzserver" pthreond_wait.S:185
  16   Thread 0x7fffb9c2f700 (LWP 7605) "gzserver" pthreond_wait.S:185
  15   Thread 0x7fffbb7fe700 (LWP 7586) "gzserver" pthre
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  13   Thread 0x7fffd0ff9700 (LWP 7583) "gzserver" pthre
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  12   Thread 0x7fffd17fa700 (LWP 7582) "gzserver" pthre
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  11   Thread 0x7fffd1ffb700 (LWP 7581) "gzserver" pthre
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  10   Thread 0x7fffd27fc700 (LWP 7580) "gzserver" pthre
_2.3.2 ()
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  9    Thread 0x7fffd2ffd700 (LWP 7579) "gzserver" pthre
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  8    Thread 0x7fffd37fe700 (LWP 7578) "gzserver" pthre
    at ../nptl/sysdeps/unix/sysv/linux/x86_64/pthread_co
  7    Thread 0x7fffd3fff700 (LWP 7565) "gzserver" pthreond_wait.S:185
  6    Thread 0x7fffd8ffd700 (LWP 7564) "gzserver" 0x000
    () at ../sysdeps/unix/syscall-template.S:81
  5    Thread 0x7fffd97fe700 (LWP 7563) "gzserver" 0x000
    () at ../sysdeps/unix/syscall-template.S:81
  4    Thread 0x7fffd9fff700 (LWP 7560) "gzserver" __clo
    clock_id=0, flags=0, req=0x7fffd9ffecf0, rem=0xfffff
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
  3    Thread 0x7fffda800700 (LWP 7559) "gzserver" 0x000
  2    Thread 0x7fffdef35700 (LWP 7551) "gzserver" pthreond_wait.S:185
  1    Thread 0x7ffff7f7c880 (LWP 7456) "gzserver" __clo
    clock_id=0, flags=0, req=0x7fffffffcef0, rem=0xfffff
---Type <return> to continue, or q <return> to quit---
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:49
(gdb) Quit
```

**Comment by k-okada** [comment]
ok, I have added example code, please check with following,

```
roslaunch gazebo_ros empty_world.launch world_name:=`rospack find gazebo_plugins`/test/test_worlds/gazebo_ros_planar_move_2.world
```

**Comment by k-okada** [comment]
@hsu please review

**Comment by 130s** [comment]
This addresses an existing issue #121 so I suggest this to be reviewed before the new release.

**Comment by ahcorde** [comment]
PR open since 2016, no feedback since 2016 and targeting and unsupported release. Closing this, feel free to reopen in a supported version if the PR is still relevant.

**Pull request closed without merging**
