### PR TITLE
[backport][ros2] make transient local reliable (#1033) (#1036)

### PR DESCRIPTION
**Pull request by Karsten1987**
* [ros2] make transient local reliable (#1033)

* make transient local reliable

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* fix master

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* add launch test

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* make it actual latched

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* alpha sort

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* add launch_test dependency

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* more dependencies

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* remove debug print

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* is_initialized -> ok

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* Update gazebo_ros/test/entity_spawner.test.py

Co-Authored-By: chapulina <louise@openrobotics.org>

* use erase-remove idiom

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

* use ReadyToTest()

Signed-off-by: Karsten Knese <karsten@openrobotics.org>

Co-authored-by: chapulina <louise@openrobotics.org>

* Set timeout and call gzserver directly

Signed-off-by: Louise Poubel <louise@openrobotics.org>

Co-authored-by: chapulina <louise@openrobotics.org>

### CODE REVIEW

**Comment by chapulina** [comment]
CI [Build Status](https://ci.ros2.org/job/ci_linux/9300/)

**Comment by Karsten1987** [comment]
internal compiler error, re-triggering previous CI:
[Build Status](https://ci.ros2.org/job/ci_linux/9301/)

**Comment by chapulina** [comment]
@Karsten1987 , I don't remember exactly what this PR was about. Is it up-to-date?

**Comment by Karsten1987** [comment]
I mentioned this to you somewhere (don't remember where) but the fix on the eloquent branch was never correctly forward ported. I think we should close this PR and compose a list of commits to cherry-pick in a new PR.

**Comment by chapulina** [comment]
Closing in favour of #1129

**Pull request closed without merging**
