### PR TITLE
Header for GetModelState service request for jade-devel

### PR DESCRIPTION
**Pull request by maxbader**
Hi as requested by hsu there is the new pull request releated to  #259 for the GetModelState service request.

### CODE REVIEW

**Comment by hsu** [comment]
Thanks!

**Comment by maxbader** [comment]
Can we close this one with a merge?

**Comment by maxbader** [comment]
Sorry for bordering again.
But I think that ModelState needs at least a timestamp because of the unpredictable network delays.

**Comment by wjwwood** [comment]
Sorry, I was shuffling around the branches and this got closed. @hsu you should consider this for Jade in the near future.

**Pull request merged**
