### PR TITLE
Port fix_build branch for indigo-devel (fix compilation for gazebo4)

### PR DESCRIPTION
**Pull request by j-rivero**
I've ported the pull request #221 and target it to indigo. It is not exactly the same, some changes are not needed in the indigo branch.

//cc @nkoenig @hsu @adolfo-rt

### CODE REVIEW

**Comment by scpeters** [comment]
I fixed a few more deprecation warnings for gazebo 4 in c95a9c1

**Comment by hsu** [comment]
Jose, did you take a look at the compatibility_gazebo_4.0 branch? and there's one for hydro too (compatibility_gazebo_4.0_hydro)

**Comment by scpeters** [comment]
@hsu I think this branch is a little bit cleaner and fixes all the warnings. You removed PCL in that branch in one place, but that is being taken care of by #180 (which looks really good to me; I just don't know how to test it).

**Comment by hsu** [comment]
+1
just went through the diff, this one is more complete. Thanks!

**Comment by scpeters** [comment]
+1

**Comment by adolfo-rt** [comment]
The `gazebo_ros_control` part looks fine.

**Pull request merged**
