### PR TITLE
Header for GetModelState service request

### PR DESCRIPTION
**Pull request by maxbader**
Hi

I added a general header to the GetModelState.srv and some lines to the gazebo_ros_api_plugin.cpp which to get a actural time stamp to a model request.
I did this to fix the model state to the simlated time which is needed in many cases
I think my work would also be downward compatibel.

Greetings
Markus

PS.: I would suggest to do the same thing for the ModelStates.msg or ModelState.msg

### CODE REVIEW

**Comment by maxbader** [comment]
Anybody interested?

**Comment by adolfo-rt** [comment]
Take into account that modifying non-comment parts of a message specification will change its MD5 sum. Even if the changes you propose are relevant, they would have to be applied to the next ROS distro (jade-turtle) for message compatibility reasons.

**Comment by hsu** [comment]
created jade-devel branch, please retarget. thanks!

**Comment by hsu** [comment]
Hi @maxbader can you recreate the pull request to target jade-devel?
thanks.

**Comment by maxbader** [comment]
Hi @hsu I created an other pull request for jade-devel. have a look at the pull request nr #302.
If 302 you can reject this one or I will close it.

**Comment by scpeters** [comment]
#302 merged instead

**Pull request closed without merging**
