### PR TITLE
[forward port] publish with QoS reliable as default (#1224)

### PR DESCRIPTION
**Pull request by jacobperron**
Port #1224 to Rolling.

Default all ROS publishers in plugins to reliable QoS.

### CODE REVIEW

**Review by scpeters — APPROVED** [review]
looks good; I believe the cmake linting errors are already fixed by #1249

**Comment by jacobperron** [comment]
@osrf-jenkins run tests please

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Comment by jacobperron** [comment]
@ros-pull-request-builder retest this please

**Pull request merged**
