### PR TITLE
Update gazebo script

### PR DESCRIPTION
**Pull request by nkoenig**
We should really use the `gazebo` program, and not a separate `gzsever` and `gzclient`.

This pull request is dependent on this [gazebo pull request](https://bitbucket.org/osrf/gazebo/pull-requests/2387), and a new release of gazebo7.

### CODE REVIEW

**Comment by hsu** [comment]
+1

**Comment by scpeters** [comment]
It's a problem if this pull request requires a new release of `gazebo7`, since kinetic uses the Ubuntu version of gazebo 7.0.0 by default.

**Comment by nkoenig** [comment]
Can't make this change to kinect.

**Comment by nkoenig** [comment]
A proposed alternative is `kill -n 2` instead of `kill -s $SIGNAL`

**Comment by scpeters** [comment]
`kill -n 2` is less readable, but hopefully more robust

**Pull request closed without merging**
