### PR TITLE
gazebo_ros: Use relative namespace for performance metrics

### PR DESCRIPTION
**Pull request by mitschron**

### CODE REVIEW

**Review by chapulina — CHANGES_REQUESTED** [review]
I don't think this will work. Gazebo is publishing at an exact topic without a namespace:

https://github.com/osrf/gazebo/blob/10863ffa8ec28e8e0e3d3a3a588d21cdc78055ab/gazebo/sensors/SensorManager.cc#L186

Also, the `~` will resolve to `/gazebo/worldname`, not just `/gazebo`.

Are you trying to solve some issue?

**Comment by mitschron** [comment]
> I don't think this will work. Gazebo is publishing at an exact topic without a namespace:
> 
> https://github.com/osrf/gazebo/blob/10863ffa8ec28e8e0e3d3a3a588d21cdc78055ab/gazebo/sensors/SensorManager.cc#L186
> 
> Also, the `~` will resolve to `/gazebo/worldname`, not just `/gazebo`.
> 
> Are you trying to solve some issue?

Please have a look at issue #1175. Adding the performance metrics seems to be breaking the plugins.

**Comment by scpeters** [comment]
> > I don't think this will work. Gazebo is publishing at an exact topic without a namespace:
> > https://github.com/osrf/gazebo/blob/10863ffa8ec28e8e0e3d3a3a588d21cdc78055ab/gazebo/sensors/SensorManager.cc#L186
> > Also, the `~` will resolve to `/gazebo/worldname`, not just `/gazebo`.
> > Are you trying to solve some issue?
> 
> Please have a look at issue #1175. Adding the performance metrics seems to be breaking the plugins.

I believe the underlying issue in #1175 is https://github.com/osrf/gazebo/issues/2902, and it can occur whenever there is a subscriber to the gazebo topic `/gazebo/performance_metrics` and gazebo's `SensorManager` has sensors in 2 or more `SensorContainer`s (ie a camera and a lidar, or a lidar and an IMU). This pull request works around the issue by breaking the gazebo subscriber so that it subscribes to an incorrect topic. I've submitted a different workaround in #1202 to `noetic-devel` (and #1203 for melodic and #1205 for `ros2`) that only subscribes to the gazebo topic if there is anyone subscribing to the corresponding ROS topic. So it will still be possible to encounter the deadlock, but it requires an extra step of subscribing to the `/performance_metrics` topic. I've opened #1209 to backport this workaround to `kinetic-devel`, so I think this can be closed once that is merged.

**Comment by scpeters** [comment]
I'm going to close this since I've just merged #1209 to `kinetic-devel`, and I believe it's a suitable workaround to #1175

**Pull request closed without merging**
