### PR TITLE
Added a sonar gazebo ros plugin

### PR DESCRIPTION
**Pull request by mrmouss**
Hi,
As discussed in issue #694 here is the code I have written to implement a gazebo sonar plugin which is different in behavior than the often used gazebo_ros_range plugin.
One major limitation is that the sonar sensor is probably developed for a drone use which may explain the main z-negative measuring axis. Hence, if you want to correctly visualize the measurement in Rviz you need to hack for your URDF file as I will explain in the following:

    <joint name="sonar_joint" type="fixed">
        <origin xyz="0.1 0 .01" rpy="0 0 0"/>
        <parent link="base_link" />
        <child link="sonar_link" />
    </joint>

    <link name="sonar_link" />

	

	<joint name="sonar_joint_fake" type="fixed">
        <origin rpy="0 ${-pi/2} 0"/>
        <parent link="sonar_link" />
        <child link="sonar_link_fake" />
	</joint>

	<link name="sonar_link_fake"/>

So what we did above is defining a fake joint and a fake link with a negative z-axis pointing out to the direction that we need to measure its distance as explained in the following screenshot:

screenshot at 2018-04-04 20 00 44

For the Gazebo section in your URDF you need to specify two different links for your sonar sensor, the first one is the one used for rviz visualization while the second one is for Gazebo using the created 'fake' link:

        <gazebo reference="sonar_link_fake">

            <sensor type="sonar" name="sonar">

                <always_on>1</always_on>
                <update_rate>10</update_rate>
                <visualize>true</visualize>
                <topic> sonar_scan </topic>
                <sonar>
                    <min>0.01</min>
                    <max>2.0</max>
                    <radius>0.26</radius>
                </sonar>

                <plugin name="us_plugin_sonar" filename="libgazebo_ros_sonar.so" >
                    <gaussianNoise>0.005</gaussianNoise>
                    <topicName>sonar_scan</topicName>
                    <frameName>sonar_link</frameName>
                    <fov>0.26</fov>
                </plugin>

                </sensor>

        </gazebo>

The obtained result in gazebo and rviz is shown in the following screenshots:

screenshot at 2018-04-04 20 02 36

screenshot at 2018-04-04 20 06 06

Let me know if something isn't clear to you.

### CODE REVIEW

**Comment by j-rivero** [comment]
Thanks for the contributions, looks great!

Could you please attach a world example that uses this plugin?

**Comment by mrmouss** [comment]
Sorry but I don't know how to do that. I mainly work with URDF files and what I provided above is enough to write a basic URDF file and launch it with urdf_spawner. Let me know if that works for you so I write the xacro and launch files for you.

**Comment by j-rivero** [comment]
> Sorry but I don't know how to do that. I mainly work with URDF files and what I provided above is enough to write a basic URDF file and launch it with urdf_spawner. Let me know if that works for you so I write the xacro and launch files for you.

Having a launch file that brings the new sensor to the simulator should be enough yes. Possibly what you usually use to test your development. I can do the rest of something more needs to be done.

Thanks.

**Comment by mrmouss** [comment]
Here you go. Let me know if you had any issues.
[test_sonar_plugin.zip](https://github.com/ros-simulation/gazebo_ros_pkgs/files/1899435/test_sonar_plugin.zip)

**Comment by mrmouss** [comment]
One more thing I forgot to add is 'gazebo_ros_sonar' in 'catkin_package(...)' section in the CMakeLists.txt file.

**Comment by kev-the-dev** [comment]
@mbennehar you can amend your PR after submitting it by pushing new commits to your branch. If you do this for the zip file and cmakelist changes you mentioned we can proceed with the review.

**Comment by john-bessire** [comment]
When running test_sonar_plugin.zip using ROS kinetic and Gazebo7 I get the following error messages for velocity_controller and diff_drive_controller during roslaunch.  It still loads RVIZ and Gazebo.

    [INFO] [1530667833.355429, 0.046000]: Loading controller: velocity_controller
    [ERROR] [1530667833.420633540, 0.053000000]: Could not load controller 'velocity_controller'   because controller type 'diff_drive_controller/DiffDriveController' does not exist.
    [ERROR] [1530667833.420830684, 0.054000000]: Use 'rosservice call controller_manager/list_controller_types' to get the available types
    Exception in thread /clock (most likely raised during interpreter shutdown):
    Traceback (most recent call last):
      File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
      File "/usr/lib/python2.7/threading.py", line 754, in run
      File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_pubsub.py", line 185, in robust_connect_subscriber
      File "/opt/ros/kinetic/lib/python2.7/dist-packages/rospy/impl/tcpros_base.py", line 823, in receive_loop
    <type 'exceptions.TypeError'>: 'NoneType' object is not callable

I attempted to install both the velocity and diff_drive controllers but the packages were not found.
    
    sudo apt-get install ros-kinetic-diff_drive_controller
    E: Unable to locate package ros-kinetic-diff_drive_controller

    sudo apt-get install ros-kinetic-velocity_controller
    E: Unable to locate package ros-kinetic-velocity_controller



`

**Comment by j-rivero** [comment]
> I attempted to install both the velocity and diff_drive controllers but the packages were not found.
> 
> sudo apt-get install ros-kinetic-diff_drive_controller
> E: Unable to locate package ros-kinetic-diff_drive_controller
> 
> sudo apt-get install ros-kinetic-velocity_controller
> E: Unable to locate package ros-kinetic-velocity_controller

Note that debian packages don't allow the use on underscores, could you give  try to:
`sudo apt-get install ros-kinetic-velocity-controller  ros-kinetic-diff-drive-controller`

**Comment by KaranJagdale** [comment]
I don't have experience of working with URDF file can someone tell how to do this with sdf file?

**Comment by Seanmatthews** [comment]
Any updates on this?

**Comment by corot** [comment]
> Any updates on this?

Hey,,, are you currently using this plugin? I have tried with latest gazebo 9.16 and melodic and makes gazebo crash:

```
#0  0x00007fffec449355 in  () at /usr/local/lib/libgazebo_ode.so.9
#1  0x00007fffec455e3c in  () at /usr/local/lib/libgazebo_ode.so.9
#2  0x00007fffec455e29 in  () at /usr/local/lib/libgazebo_ode.so.9
#3  0x00007fffec455d89 in  () at /usr/local/lib/libgazebo_ode.so.9
#4  0x00007fffec4570a7 in  () at /usr/local/lib/libgazebo_ode.so.9
#5  0x00007fffec4575b3 in dSpaceCollide2 () at /usr/local/lib/libgazebo_ode.so.9
#6  0x00007ffff551bff8 in gazebo::physics::ODEMultiRayShape::UpdateRays() () at /usr/local/lib/libgazebo_physics.so.9
#7  0x00007ffff5626123 in gazebo::physics::MultiRayShape::Update() () at /usr/local/lib/libgazebo_physics.so.9
#8  0x00007ffff604a157 in gazebo::sensors::RaySensor::UpdateImpl(bool) () at /usr/local/lib/libgazebo_sensors.so.9
#9  0x00007ffff60509d5 in gazebo::sensors::Sensor::Update(bool) () at /usr/local/lib/libgazebo_sensors.so.9
#10 0x00007ffff6057516 in gazebo::sensors::SensorManager::SensorContainer::Update(bool) () at /usr/local/lib/libgazebo_sensors.so.9
#11 0x00007ffff6058956 in gazebo::sensors::SensorManager::SensorContainer::RunLoop() () at /usr/local/lib/libgazebo_sensors.so.9
#12 0x00007ffff310bbcd in  () at /usr/lib/x86_64-linux-gnu/libboost_thread.so.1.65.1
#13 0x00007ffff594a6db in start_thread (arg=0x7ffef4b9f700) at pthread_create.c:463
#14 0x00007ffff63c471f in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
```

I have cherry-picked your commits instead of using your branch, because you branched from kinetic. Did you update this plugin to melodic?  If so, I'll be happy to give it a try
Thanks!

**Pull request closed without merging**
