### PR TITLE
gazebo_ros_control: default_robot_hw_sim: Suppressing pid error message

### PR DESCRIPTION
**Pull request by jbohren**
This depends on ros-controls/control_toolbox#21

### CODE REVIEW

**Comment by jonbinney** [comment]
+1

Looks like the PR it depends upon has been merged already, too.

**Comment by mikeferguson** [comment]
FYI, the PR this depends on is in indigo-devel ONLY. This probably shouldn't be merged into hydro-devel of gazebo_ros_pkgs

**Comment by davetcoleman** [comment]
@mikeferguson I ran into that issue too - this no longer compiles in hydro. The fix is https://github.com/ros-controls/control_toolbox/pull/23 but perhaps this should have never been merged into hydro-devel.

**Comment by jonbinney** [comment]
Yeah - I missed that. Thought this was going into indigo-devel

**Comment by davetcoleman** [comment]
So should we undo or move forward? I'm not sure.

**Comment by jonbinney** [comment]
I think merging a commit that reverses this change right now is the thing to do. Later if the control_toolbox thing gets merged into hydro we can always add this back here, but most important thing is getting gazebo_ros_pkgs to build now.

**Comment by mikeferguson** [comment]
+1 to reversing, see my comments on https://github.com/ros-controls/control_toolbox/pull/23

**Comment by davetcoleman** [comment]
+1 reversing after reading @mikeferguson's comments
@jbohren can you create a commit to undo this, and make a new request to the indigo-branch please?

**Comment by adolfo-rt** [comment]
You are right @mikeferguson, the changes merged into control-toolbox (indigo-devel) break ABI compatibility, so can't be backported to hydro-devel. Since I was the one that merged the PR, I'll take responsibility for the fix, which is a one-liner. standby.

**Comment by davetcoleman** [comment]
Perfect, thanks @adolfo-rt, I believe everything is settled now aside from releasing to bloom.

**Pull request merged**
