### PR TITLE
Issue #213

### PR DESCRIPTION
**Pull request by curranw**
Added an XML argument to the Diff Drive plugin to allow the turning on/off of tf/topic publishing for odometry.

### CODE REVIEW

**Comment by hsu** [comment]
This changes the default behavior to turn off publishing tf without `<publishTF>`.  Is this expected?

**Comment by curranw** [comment]
No that was a mistake. Default behavior switched. Now the change shouldn't affect anyone unless explicitly changed.

**Comment by hsu** [comment]
Thanks for the update. Looks good.

**Comment by hsu** [comment]
merging in #230

**Pull request closed without merging**
