### PR TITLE
Publish camera info in gazebo_ros_depth_camera plugin

### PR DESCRIPTION
**Pull request by ongun-kanat**
`PublishCameraInfo()` function was created but it wasn't used. I needed camera info to be published. It might be useful for other people too. 

Thanks for review.

### CODE REVIEW

**Review by kev-the-dev — APPROVED** [review]
Addresses  issue #569.

This is also fixed by my refactor in #757, but this is a good change in the mean time.

CI failure is unrelated.

**Comment by chapulina** [comment]
Just saw that this has been approved for a long time but never merged. Merging!

**Comment by ongun-kanat** [comment]
Ah thanks @chapulina . I've forgotten about it and hence didn't bump it. BTW #569 and #570 seem to be related to this and might need attention too.

**Comment by c-rizz** [comment]
Hi, I'm on noetic and camera info is not being published for depth. Looking at the code it looks like this has been merged in kinetic, but not in melodic-devel and noetic-devel.

**Comment by ongun-kanat** [comment]
@c-rizz Apparently  @kev-the-dev 's refactoring should fix it. But it doesn't seem to be merged yet.

**Pull request merged**
