### PR TITLE
Adding hand-of-god plugin

### PR DESCRIPTION
**Pull request by jbohren**
This PR adds a plugin which makes it easy to attach a rigid object to a TF frame and move it around in simulation.

### CODE REVIEW

**Comment by hsu** [comment]
Thanks Jon, nice name for a plugin.  Do you have an example on how this is used?  Or some doxygen style documentation would be nice.  I am guessing `kl` and `ka` are stiffness coefficients connecting _hand of god_ to the model, and `cl` and `ca` are related to corresponding damping coefficients?

**Comment by hsu** [comment]
`err_pos` is the position error in the frame of the `floating_link_`, if you need it in world frame, you can do

```
    // position error from floating link position to hog position in world frame
    gazebo::math::Vector3 err_pos = world_pose.rot.RotateVector(hog_desired.pos - world_pose.pos);
```

Also, I have a question relating to `err_rot`, why use `x,y,z` components of a quaternion (`ka_ * gazebo::math::Vector3(not_a_quaternion.x, not_a_quaternion.y, not_a_quaternion.z)`) as opposed to getting the logarithm of Euler angles for torque application?

Thanks.

**Comment by jbohren** [comment]
> Also, I have a question relating to `err_rot`, why use `x,y,z` components of a quaternion (`ka_ * gazebo::math::Vector3(not_a_quaternion.x, not_a_quaternion.y, not_a_quaternion.z)`) as opposed to getting the logarithm of Euler angles for torque application?

I am using the matrix logarithm, except for some reason the gazebo API returns them as a `Quaternion` data structure with `w=0` .

**Comment by hsu** [comment]
Are you getting expected rotational control results?  If not, might `(ka_ * not_a_quaternion.GetAsEuler())` behave better?  (might have to skip `GetLog()` on `not_a_quaternion` and take the logarithms on individual Euler angles)

**Comment by jbohren** [comment]
> Are you getting expected rotational control results?  

Yeah, the rotational servoing is fine. 

> If not, might `(ka_ * not_a_quaternion.GetAsEuler())` behave better?  (might have to skip `GetLog()` on `not_a_quaternion` and take the logarithms on individual Euler angles)

I'm not calling `GetLog()` on `not_a_quaternion`, I'm calling it on the relative rotation in SO(3) (represented as a `math::Quaternion`) and getting out a 4-tuple `not_a_quaternion = (0,wx,wy,wz)` which is the related element in so(3) with a zero prefixed to it.

**Comment by jbohren** [comment]
Any reason why this shouldn't be accepted/merged?

**Comment by hsu** [comment]
Looks good, one minor update, install to target:

```
diff --git a/gazebo_plugins/CMakeLists.txt b/gazebo_plugins/CMakeLists.txt
index d4e097b..3e89a63 100644
--- a/gazebo_plugins/CMakeLists.txt
+++ b/gazebo_plugins/CMakeLists.txt
@@ -248,6 +248,7 @@ install(TARGETS
   gazebo_ros_imu
   gazebo_ros_f3d
   gazebo_ros_bumper
+  gazebo_ros_hand_of_god
   gazebo_ros_template
   gazebo_ros_projector
   gazebo_ros_prosilica
```

**Comment by jbohren** [comment]
Ah good call. I'll add that and then merge.

**Comment by hsu** [comment]
thanks +1 for merge

**Comment by jbohren** [comment]
Added install target, merging now...

**Pull request merged**
