### PR TITLE
add launch files for spawning models at gazebo world

### PR DESCRIPTION
**Pull request by YoheiKakiuchi**
Add launch files for spawning models, such as box, cylinder, model in database.

### CODE REVIEW

**Comment by hsu** [comment]
What is the specific use case you need these launch files for?
thanks.

**Comment by furushchev** [comment]
+1

**Comment by furushchev** [comment]
I think this launch file is for spawning many kinds of models from gazebo database by changing only launch file.
This is very useful when writing test codes that needs specific scenario.

**Comment by scpeters** [comment]
The box and cylinder launch files do not have inertia values specified. Can you add reasonable values?

**Comment by ahcorde** [comment]
Very old PR from 2014, targeting a not supported ROS version, closing this

**Pull request closed without merging**
