### PR TITLE
create GazeboRosCameraUtils::GetCameraInfo and test getting camera in…

### PR DESCRIPTION
**Pull request by scpeters**
…formation from gazebo Camera object to see if it updates when we change camera resolution on the fly.

### CODE REVIEW

**Comment by hsu** [comment]
+1

**Comment by scpeters** [comment]
This was your branch. Can you describe a little bit more what is happening? Also, there are some `\TODO` statements. Can you elaborate on what is needed to mark them as complete?

**Comment by j-rivero** [comment]
run test please

**Comment by scpeters** [comment]
this is old, and I'm not sure if it's still needed, so I'm going to close it

**Pull request closed without merging**
