### PR TITLE
Merge hydro into groovy

### PR DESCRIPTION
**Pull request by davetcoleman**
There are some users who wish to continue to use gazebo_ros_pkgs with ROS Groovy, and so to make development and bug fixes easier in the short term, I have made the two branches be clones of each other. This was accomplished by using compiler conditions `#if` for the different function calls for PCL 1.6 (Groovy) and PCL 1.7 (Hydro).

@wjwwood @rethink-cgindel @hsu

### CODE REVIEW

**Comment by davetcoleman** [comment]
@wjwwood do I need to add pcl to my package.xml and CMakeList.txt as a catkin depend?

**Comment by wjwwood** [comment]
`pcl` needs to be in the package.xml, but it is not a catkin package, you should continue to `find_package(PCL REQUIRED)` in your `CMakeLists.txt`.

**Comment by wjwwood** [comment]
Looks fine to me, the implementation that is. The solution is a mess, but it's the only solution I think.

**Comment by davetcoleman** [comment]
I added pcl to package.xml

**Pull request merged**
