### PR TITLE
hog: making only the hand of god link zero-g. 

### PR DESCRIPTION
**Pull request by jbohren**
this lets you use the hand of god on a single link in a gravity-affected model

### CODE REVIEW

**Comment by hsu** [comment]
should we add an optional sdf element for the plugin to indicate if either the model or the link gravity should be turned off? And default to the old behavior (model)?

**Comment by scpeters** [comment]
We can get this in kinetic if you respond to John's feedback by Wednesday.

**Comment by hsu** [comment]
+1

I am OK for merging into hydro-devel branch, and merge forward. Or if you want to retarget for indigo or jade that works for me too.

This pr does not affect api, so I think we can always merge it into kinetic later right?

**Comment by j-rivero** [comment]
we don't plan to merge forward hydro. Not a bugfix so lets put this in jade directly.

**Pull request closed without merging**
