### PR TITLE
Compatibility gazebo 4.0

### PR DESCRIPTION
**Pull request by hsu**

### CODE REVIEW

**Comment by jonbinney** [comment]
@hsu what's the easiest way to test this against various versions of gazebo? Do you install gazebo to a CMAKE_INSTALL_PREFIX? Or have you wrapped it with a package.xml so that you can include it in catkin workspaces? Or do you sudo make install each version of gazebo?

**Comment by jonbinney** [comment]
And did you mean to make this PR against hydro-devel?

**Comment by hsu** [comment]
@jonbinney, good point, this should go to i or j-turtle.  closing pr.

Yes, I usually install gazebo to a local `CMAKE_INSTALL_PREFIX`, add the appropriate CMAKE_MODULE_PREFIX, PATH, LD_LIBRARY_PATH, LIBRARY_PATH, etc. send me an email, I can provide more detail.

**Comment by scpeters** [comment]
@jonbinney I have some [package.xml files](https://bitbucket.org/scpeters/unix-stuff/src/master/package_xml/) that I use for building gazebo and some of its dependencies in catkin workspaces.

**Comment by jonbinney** [comment]
Nice, I will be stealing those....

**Comment by jonbinney** [comment]
I'm sure it's been mentioned before, but if those package.xml's were added to the actual repos, it would make building gazebo with ROS really easy, without actually hurting anything... just sayin'...

**Comment by scpeters** [comment]
@jonbinney There's an [open issue](https://bitbucket.org/osrf/gazebo/issue/833/support-building-in-catkin-workspaces) on bitbucket. Please upvote it if you would like the package.xml's in gazebo and sdformat repositories. Feel free to encourage others to vote as well.

EDIT: the issue is "On hold" but people can still vote for it.

**Pull request closed without merging**
