### PR TITLE
Remove useless cmake code in tests

### PR DESCRIPTION
**Pull request by j-rivero**

### CODE REVIEW

**Comment by scpeters** [comment]
Why is that cmake code useless? Just curious

**Comment by j-rivero** [comment]
Sorry for the empty the description. Looks to me like the gazebo_msgs_gencpp dependency does not currently exists.  `The dependency target "gazebo_msgs_gencpp" of target "gazebo_ros_bumper" does not exist.` in the CI log.

**Comment by scpeters** [comment]
This looks like a different fix than #404. Should this match that PR?

**Comment by j-rivero** [comment]
let's merge forward indigo and get #404

**Pull request closed without merging**
