### PR TITLE
Remove compiler directive flags for < GAZEBO 7

### PR DESCRIPTION
**Pull request by davetcoleman**
Based on [comment](https://github.com/ros-simulation/gazebo_ros_pkgs/pull/540#discussion_r101412334) by @j-rivero 

*This PR is sponsored by [Vicarious](http://www.vicarious.com/)*

### CODE REVIEW

**Comment by davetcoleman** [comment]
Merge conflict resolved

**Comment by j-rivero** [comment]
Just for double checking: @scpeters could you see any use case where we need gazebo < 7 in the kinetic branch?

**Comment by gavanderhoorn** [comment]
Is there a specific reason *not* to leave these guards in there? Is there anything that breaks if we leave them in?

**Comment by j-rivero** [comment]
> Is there a specific reason not to leave these guards in there?

Less code, easy maintenance. My opinion is that the number of cases where the people is using the kinetic branch with versions lower than gazebo7 is really limited.

> Is there anything that breaks if we leave them in?

Not really. It will cost a little bit more of contributors time when making changes and could drive to confusion while looking or search the code.

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
> Is there a specific reason not to leave these guards in there? Is there anything that breaks if we leave them in?

@gavanderhoorn before merging, do you have any use case in which you need the guards? If so, I'm interested in knowing it before kill them.

**Comment by gavanderhoorn** [comment]
No,  don't have a use-case here. I was just wondering if this was a case of removing code for the sake of removing it.

Feel free to merge.

**Comment by scpeters** [comment]
I don't think we need to keep support for gazebo6 or earlier on kinetic. This looks like a good idea to me.

**Comment by davetcoleman** [comment]
The broken builds are too old and unviewable, can someone re-trigger the CI build for this PR?

**Comment by scpeters** [comment]
I restarted this one:

* https://build.osrfoundation.org/job/ros_gazebo_pkgs-ci-pr_regression_any-xenial-amd64/28

I'll look into the others

**Comment by scpeters** [comment]
For the gazebo8 build, I have an email record that says the build is unstable due to compiler warnings. I believe they aren't caused by this branch, so that shouldn't be a blocker.

**Comment by scpeters** [comment]
@ros-pull-request-builder

**Comment by scpeters** [comment]
@ros-pull-request-builder  retest this please

**Review by scpeters — APPROVED** [review]

**Pull request merged**
