### PR TITLE
fix gazebo7 deprecation warnings on kinetic

### PR DESCRIPTION
**Pull request by scpeters**
I'm skipping the ifdef's for kinetic since gazebo7 is the minimum required version

### CODE REVIEW

**Comment by j-rivero** [comment]
+1. ready to merge as soon as CI finish successfully.

**Comment by j-rivero** [comment]
65 killed, [one alive](http://build.ros.org/job/Kpr__gazebo_ros_pkgs__ubuntu_xenial_amd64/16/warnings17Result/). Not bad.

**Comment by scpeters** [comment]
For some reason that doesn't give me any warnings on trusty. To remove it, I think we should remove a service that was deprecated in hydro (0fb7b71547c25e93d03126debd9659cb791b25ed):
- https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_ros/include/gazebo_ros/gazebo_ros_api_plugin.h#L144-L145
- https://github.com/ros-simulation/gazebo_ros_pkgs/blob/jade-devel/gazebo_ros/src/gazebo_ros_api_plugin.cpp#L221-L228

**Comment by scpeters** [comment]
If this is approved, I'll update the migration guide.

**Comment by scpeters** [comment]
warning is fixed

**Comment by jackieokay** [comment]
+1

**Comment by j-rivero** [comment]
Thanks Steve! I will run a new release to get this changes in as soon as possible.

**Comment by scpeters** [comment]
[migration guide updated](http://wiki.ros.org/action/info/kinetic/Migration?action=diff&rev2=11&rev1=10)

**Pull request merged**
