### PR TITLE
[ros2] Adapt sim time test to work around rclcpp issue

### PR DESCRIPTION
**Pull request by chapulina**
Work around https://github.com/ros2/rclcpp/issues/595

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by j-rivero** [comment]
Looks like we are missing a dependency on ros-rmw:
```
/opt/ros/crystal/include/rcl/context.h:23:10: fatal error: rmw/init.h: No such file or directory
 #include "rmw/init.h"
          ^~~~~~~~~~~~
```

**Comment by chapulina** [comment]
> Looks like we are missing a dependency on ros-rmw:

This error is showing up on the OSRF build farm, but this branch builds on the ROS one. I'm not sure what's the difference between them that could cause this, but I can't reproduce the issue locally.

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by nuclearsandwich** [comment]
@ros-pull-request-builder retest this please

**Review by wjwwood — APPROVED** [review]
lgtm!

**Pull request merged**
