### PR TITLE
publish organized pointcloud from openni plugin

### PR DESCRIPTION
**Pull request by garaemon**
publish pointcloud from openni as organized pointcloud.

see https://github.com/ros-simulation/gazebo_ros_pkgs/issues/210

### CODE REVIEW

**Comment by jonbinney** [comment]
This seems like it could break code that expects a 1d array of points - maybe it shouldn't go into hydro?

**Comment by garaemon** [comment]
> This seems like it could break code that expects a 1d array of points

I think the point cloud keeps 1d array even though you apply this patch.

**Comment by jonbinney** [comment]
I see what you mean - the actual array in the message will be 1d. Not sure if anyone has code which expects width and height to not be set, but it seems reasonable to call this a bugfix rather than a new feature.

**Comment by garaemon** [comment]
> Not sure if anyone has code which expects width and height to not be set

I think there may be several codes expect organized pointcloud structure and I don't think there is a code which expects `height=1`

**Pull request merged**
