### PR TITLE
Updates to the diff_drive plugin

### PR DESCRIPTION
**Pull request by maxbader**
Hi I updated the diff_drive plugin code, 
- the functions: void UpdateChild(); void FiniChild(); are not virtual!
- the virtual functions void Load(physics::ModelPtr _parent, sdf::ElementPtr _sdf); virtual void Reset(); virtual void Init(); are marked with override to prevent overriding by others and the virtual was removed
- the multi-robot test scenario was removed and replaced by the launch multi_pioneer3dx.launch
- the physical properties of the pioneer robot robot are enhanced
- the folder structure and the models are easier to reuse because the model base folder is now a argument within the xacro --> pioneer3dx.xacro
- a cave world was added
- visual markers can be places in the cave world --> visual_marker_cave.launch
  default_gzclient_camera 1 -2016-08-09t16_57_14 408360

### CODE REVIEW

**Comment by j-rivero** [comment]
Thanks Max for the changes and specially for all the implementation done for the examples. Amazing.

First impressions: 
- It would be nice to include a README in the test directory explaining which are the main launch files for running the examples.
- Small patch to propagate the verbose option to the pioneer3dx launch file:

``` diff
diff --git a/gazebo_plugins/test/diff_drive/launch/pioneer3dx/pioneer3dx.launch b/gazebo_plugins/test/diff_drive/launch/pioneer3dx/pioneer3dx.launch
index 8ed84e1..179b72d 100644
--- a/gazebo_plugins/test/diff_drive/launch/pioneer3dx/pioneer3dx.launch
+++ b/gazebo_plugins/test/diff_drive/launch/pioneer3dx/pioneer3dx.launch
@@ -8,6 +8,7 @@
   <!-- Gazebo world with environment -->
   <include file="$(find gazebo_plugins)/test/diff_drive/launch/room_world.launch">
      <arg name="physics" value="$(arg physics)" />
+     <arg name="verbose" value="$(arg verbose)" />
      <arg name="room"    value="$(arg room)"    />
   </include>

diff --git a/gazebo_plugins/test/diff_drive/launch/room_world.launch b/gazebo_plugins/test/diff_drive/launch/room_world.launch
index 4e8103d..4123ada 100644
--- a/gazebo_plugins/test/diff_drive/launch/room_world.launch
+++ b/gazebo_plugins/test/diff_drive/launch/room_world.launch
@@ -2,11 +2,13 @@
   <arg name="room" default="" />
   <arg name="world_name" default="empty_world"/>
   <arg name="physics" default="ode"/> <!-- ode, bullet, dart -->
+  <arg name="verbose" default="false" />
   <env name="GAZEBO_MODEL_PATH" value="$(find gazebo_plugins)/test/diff_drive/models/environments/:$(find gazebo_plugins)/test/diff_drive/models/visual_marker/"/> 

   <!-- Gazebo  -->
   <include file="$(find gazebo_plugins)/test/diff_drive/launch/empty_world.launch">
      <arg name="physics" value="$(arg physics)" />
+     <arg name="verbose" value="$(arg verbose)" />
      <arg name="world_name" value="$(find gazebo_plugins)/test/diff_drive/worlds/$(arg world_name).world"/>
   </include>
```
- When I try to run `roslaunch gazebo_plugins pioneer3dx.launch`

```
[Err] [SystemPaths.cc:430] File or path does not exist["/home/jrivero/code/ros/ws/pr_481/src/gazebo_ros_pkgs/gazebo_plugins/test/diff_drive/worlds/empty_world.world"]
[Err] [Server.cc:365] Could not open file[/home/jrivero/code/ros/ws/pr_481/src/gazebo_ros_pkgs/gazebo_plugins/test/diff_drive/worlds/empty_world.world]
```

Did you forget to include the `gazebo_plugins/test/diff_drive/worlds/` directory in the PR or am I doing something wrong?

**Comment by maxbader** [comment]
Hello Jose

Sorry I forgot to add the world files as you correctly assumed.

**Comment by maxbader** [comment]
Hi 
I added now also a fix to the tricycle drive plugin

**Comment by davetcoleman** [comment]
@maxbader was this PR moved elsewhere?

**Pull request closed without merging**
