### PR TITLE
[gazebo_ros_imu] Add Gaussian noise parameter for yaw angle of IMU

### PR DESCRIPTION
**Pull request by Roboterbastler**
Add parameter to simulate Gaussian noise for the yaw angle of the IMU orientation. Variance of the yaw angle in the covariance matrix is set accordingly.

### CODE REVIEW

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by kev-the-dev** [comment]
Patch to fix build error (once rebased to kinetic-devel):
```
diff --git a/gazebo_plugins/src/gazebo_ros_imu.cpp b/gazebo_plugins/src/gazebo_ros_imu.cpp
index fa0f6d6..9eef870 100644
--- a/gazebo_plugins/src/gazebo_ros_imu.cpp
+++ b/gazebo_plugins/src/gazebo_ros_imu.cpp
@@ -252,8 +252,8 @@ void GazeboRosIMU::UpdateChild()
     rot = pose.Rot();
 
     // apply yaw noise
-    math::Quaternion yaw_error;
-    yaw_error.SetFromEuler(math::Vector3(
+    ignition::math::Quaterniond yaw_error;
+    yaw_error.Euler(ignition::math::Vector3d(
         0,
         0,
         this->GaussianKernel(0, this->yaw_gaussian_noise_)
```

**Comment by bochen87** [comment]
any chances this get's merged into the next cycle?

**Comment by j-rivero** [comment]
> any chances this get's merged into the next cycle?

Sure. The only problem I could see is: how this PR is going to affect the yaw noise in current simulations for the poeple relying in the current behaviour (as far as I can tell we are changing a default value of yaw noise from `gaussian_noise_` to default to 0.0).

**Comment by bochen87** [comment]
How about this: to keep the old behavior, we let `yaw_gaussian_noise_ = gaussian_noise_` in case the `yawGaussianNoise` element is undefined?
@Roboterbastler

**Comment by Roboterbastler** [comment]
I changed the default value to the value of the gaussianNoise parameter.

**Comment by ahcorde** [comment]
targeting an [unsupported version](http://wiki.ros.org/Distributions). Closing this feel free to reopen again in a supported version if the PR is still relevant.

**Pull request closed without merging**
