### PR TITLE
[gazebo_ros_control] move declaration for DefaultRobotHWSim to header file

### PR DESCRIPTION
**Pull request by fmessmer**
This PR splits up the implementation of DefaultRobotHWSim into cpp and header file in order to be able to derive from DefaultRobotHWSim with maximum code-reuse!
(This PR is motivated by #256)

### CODE REVIEW

**Comment by davetcoleman** [comment]
+1

**Comment by adolfo-rt** [comment]
I noticed that apart from the split into header/source, some methods have also become `virtual` (which already were in the base class). Are there other noteworthy changes that I could have missed?.

**Comment by jbohren** [comment]
The `init`/`read`/`writeSim` should definitely be `virtual` if people want to derive from this class, but I don't think `registerJointLimits` needs to be. That being said, I don't think that's significant enough to block this PR.

+1

**Comment by adolfo-rt** [comment]
Good catch. @ipa-fxm, was making `registerJointLimits` virtual intentional?.

**Comment by fmessmer** [comment]
Thanks for your comments!
For my use-case, I don't need `registerJointLimits` to be virtual (I undid that in https://github.com/ipa-fxm/gazebo_ros_pkgs/commit/adaf0cf4e168139dc5667bf3041e472b6cf9411b)

However, I added the generated libraries to `catkin_package``so that sub-classes located in other packages can link against them (see https://github.com/ipa-fxm/gazebo_ros_pkgs/commit/cfd2543d17db0f0bd62307921b9f189c16a25135)

**Comment by adolfo-rt** [comment]
Could you please squash the commits as usual?. I'll then give the merge a go.

**Comment by fmessmer** [comment]
Squashed...should be good to go then...

**Comment by adolfo-rt** [comment]
Thanks!

**Pull request merged**
