### PR TITLE
fixed mistake at calculation of joint velocity

### PR DESCRIPTION
**Pull request by sabrina-heerklotz**
Hi,

To calculate the velocity of the joints the wheel radius is used instead of the wheel diameter.

Regards,
Sabrina

### CODE REVIEW

**Comment by k-okada** [comment]
sorry for asking very basic question, I thought original code is correct by

```
l = 2 * pi * radius
v[m/s] = r[rad/s] * 2 * radius
r = v / diameter
```

Do I misunderstand something?

**Comment by sabrina-heerklotz** [comment]
Hi,

Sorry for my late reply!

I think your second equation is not correct. Please have a look at my equations:

l = 2 \* pi \* radius
v[m/s] = dx / dt
r[rad/s] = dphi / dt

assuming that there is no acceleration
for a full rotation you get dx = l and dphi = 2 \* pi:
v = l / dt          => dt = l / v = 2 \* pi \* radius / v
r = 2 \* pi /dt   => dt = 2 \* pi / r

eliminating dt gives:
2\* pi \* radius / v = 2 \* pi / r
radius /v = 1/r => r = v / radius

I also checked my code with the simulator:
Using my equation my robot is moving forward with the given linear speed and not with the half of it :)

Regards,
Sabrina

**Comment by k-okada** [comment]
Yeah, exactly, you're correct.

## 

◉ Kei Okada

**Comment by hsu** [comment]
looks good
+1

**Pull request merged**
