### PR TITLE
Gazebo 11 for Foxy

### PR DESCRIPTION
**Pull request by chapulina**
Needs https://github.com/ros/rosdistro/pull/24646

Related to #1080

### CODE REVIEW

**Comment by chapulina** [comment]
@ruffsl, this branch compiles against Gazebo 11 on Focal for me. It needs https://github.com/ros-perception/vision_opencv/pull/324 though.

CC @mabelzhang @j-rivero

**Review by j-rivero — APPROVED** [review]
The CI can not work since we lack of some packages to be released https://build.osrfoundation.org/job/ros2_gazebo_pkgs-ci-default_foxy-focal-amd64/1/console .

**Review by ruffsl — APPROVED** [review]
LGTM. This seems to be working for https://github.com/ros-swg/turtlebot3_demo/pull/34 .

**Comment by chapulina** [comment]
> The CI can not work since we lack of some packages to be released

It [looks like](http://repo.ros2.org/status_page/blocked_releases_foxy.html?q=id%3D%22gazebo_ros_pkgs%22&s=6&r=1) we're only blocked by `image_common` and `vision_opencv` right now. CC @mjcarroll

**Review by jacobperron — APPROVED** [review]

**Comment by chapulina** [comment]
I believe we need this before merging: https://github.com/ros-infrastructure/reprepro-updater/pull/75

**Comment by ruffsl** [comment]
@chapulina , is this ready now?

**Pull request merged**
