### PR TITLE
[gazebo_ros] Fix for #246

### PR DESCRIPTION
**Pull request by peci1**
Fixing issue #246 in gzserver.

### CODE REVIEW

**Comment by scpeters** [comment]
I think all the scripts have this issue:

```
./gazebo_ros/scripts/debug
./gazebo_ros/scripts/gazebo
./gazebo_ros/scripts/gzclient
./gazebo_ros/scripts/gzserver
./gazebo_ros/scripts/perf
```

**Comment by peci1** [comment]
I've updated also the other affected scripts. Could you merge now?

**Comment by scpeters** [comment]
+1

**Comment by scpeters** [comment]
We try to have multiple reviews before merging. @j-rivero this looks pretty straight-forward to me. What do you think?

**Comment by j-rivero** [comment]
+1. Single quotes will block the expansion of bash variable.

**Comment by peci1** [comment]
I've received a Jenkins error log, however it seems to be completely unrelated to the changes I made.

http://jenkins.ros.org/job/devel-indigo-gazebo_ros_pkgs/ARCH_PARAM=amd64,UBUNTU_PARAM=trusty,label=devel/18/changes

**Comment by j-rivero** [comment]
There were [some problems during today](http://lists.ros.org/pipermail/ros-release/2014-October/004542.html) in the release infrastructure.

**Pull request merged**
