### PR TITLE
Replacement for #303

### PR DESCRIPTION
**Pull request by caguero**
#303

### CODE REVIEW

**Comment by wjwwood** [comment]
@ros-pull-request-builder test this please

**Comment by caguero** [comment]
@ros-pull-request-builder test this please

**Comment by scpeters** [comment]
Have you tested this?

**Comment by caguero** [comment]
Yes, I have. It works in my Xenial VM.

**Comment by scpeters** [comment]
+1, looks awesome. thanks @jbohren !

**Pull request merged**
