### PR TITLE
Fix build to account for new NodeOptions interface.

### PR DESCRIPTION
**Pull request by ghost**
[ros2/rclcpp#622](https://github.com/ros2/rclcpp/pull/622) changed the Node class constructor interface, breaking the build. This PR updates the code to build with that latest change.

### CODE REVIEW

**Comment by chapulina** [comment]
Thanks for the PR. This will break compatibility with Crystal, so we'll need to create a separate branch. I can handle that if you just confirm that is the case. Thanks!

**Comment by ghost** [comment]
Yes. This will break the Crystal build. It looks like this interface change comes in with the Dashing release.

**Comment by chapulina** [comment]
I'm trying to get CI running for this. But we'll need this merged first: https://github.com/ros-perception/image_common/pull/120

**Comment by chapulina** [comment]
Got CI to build, but there are a few test failures. I haven't checked if the tests are caused by the move to Dashing or by the different CI setup.

[Build Status](https://ci.ros2.org/job/ci_linux/6511/)

---

For future reference, this is how someone with access to ci.ros2.org would run CI:

* Use this job: https://ci.ros2.org/job/ci_linux/
* Use a `ros2.repos` supplement like [this one](https://bitbucket.org/!api/2.0/snippets/chapulina/AeBk5n/410fc2655b33d8b6a3ce893e5f707967784137ea/files/ros2.repos), which has `gazebo_ros_pkgs`, `image_common` and `vision_opencv`.
* Use the [gazebo_ros_pkgs branch](https://github.com/ros2/ci/compare/master...gazebo_ros_pkgs) from `ros2/ci`so that all dependencies are installed, and other necessary dependencies are not ignored.

**Comment by chapulina** [comment]
New build now that https://github.com/ros-perception/image_common/pull/120 is in: [Build Status](https://ci.ros2.org/job/ci_linux/6519/)

**Review by chapulina — APPROVED** [review]
This fixes the build, so we should get it in. At some point before the Dashing release we'll need to fix the new linter errors and check what's causing all the new test failures though.

**Pull request merged**
