### PR TITLE
Fix get physics properties non ode

### PR DESCRIPTION
**Pull request by hsu**

### CODE REVIEW

**Comment by j-rivero** [comment]
Given the list of commits should we point this PR to indigo-devel instead of hydro-devel?

**Comment by j-rivero** [comment]
If I use this branch, the problem when using simbody is gone. Thanks.

**Comment by hsu** [comment]
@j-rivero you're right, should go to indigo-devel, thanks.

**Comment by hsu** [comment]
reopened with indigo-devel as #232

**Pull request closed without merging**
