### PR TITLE
Thermal plugin.

### PR DESCRIPTION
**Pull request by s-noda**
This plugin simulates and computes the thermal propagation of motor in accordance with the following equations:

atmosphere:   Co dTo = (Tc-To)/Ro
motor case :   Cc dTc = (To-Tc)/Ro + (Ti-Tc)/Ri
motor coil    :   Ci dTi = (Ti-Tc)/Ri + I E

where, C=thermal conductance, R=thermal resistance, I=electric current, E=electric resistance, T=temperature.

example;
add the following lines into urdf file.

```
<gazebo reference="LLEG_JOINT3">
    <provideFeedback>1</provideFeedback>
  </gazebo>
  <gazebo>
    <plugin filename="libThermoPlugin.so" name="thermo_plugin">
      <robotname>HRP2JSKNT</robotname>
      <jointname>LLEG_JOINT3</jointname>
    </plugin>
  </gazebo>
```

then, you can find the following topics. 
All of them have the message type of std_msgs::float32.

/HRP2JSKNT/thermo_plugin/LLEG_JOINT3/thermo/case
/HRP2JSKNT/thermo_plugin/LLEG_JOINT3/thermo/coil
/HRP2JSKNT/thermo_plugin/LLEG_JOINT3/torque

---

This change is [Reviewable](https://reviewable.io/reviews/ros-simulation/gazebo_ros_pkgs/253)

### CODE REVIEW

**Comment by hsu** [comment]
Please add
- [ ] license header (BSD or Apache 2.0)
- [ ] a test scenario with launch file

otherwise, it looks great! thank you.

**Comment by nkoenig** [comment]
I'm moving the core of this code to the main gazebo repository, and will write a wrapper for `gazebo_ros_pkgs`

**Comment by nkoenig** [comment]
The motor_thermal branch in this repository will eventually replace this pull request. The new plugin will use Gazebo's MotorThermalPlugin in [this branch](https://bitbucket.org/osrf/gazebo/branch/motor_thermal).

**Comment by hsu** [comment]
@nkoenig Thanks for the port to Gazebo. Are you planning on making a PR for temperature classes soon?

**Comment by nkoenig** [comment]
I'm waiting until we clear all existing pull requests.

**Comment by nkoenig** [comment]
First part of this pull request has been submitted to gazebo [here](https://bitbucket.org/osrf/gazebo/pull-requests/2283)

**Comment by j-rivero** [comment]
A quick update: the gazebo upstream code process is at this point waiting in the [ignition-math repository](https://bitbucket.org/ignitionrobotics/ign-math/pull-requests/104/temperature/diff).

**Comment by ahcorde** [comment]
This PR is from 2014, without activity in the last 6 years. Closing this

**Pull request closed without merging**
