### PR TITLE
Forward port dashing -> ros2

### PR DESCRIPTION
**Pull request by jacobperron**
Cherry-picked the commits from `dashing` that appeared to be missing in `ros2`.

### CODE REVIEW

**Comment by jacobperron** [comment]
Linux: [Build Status](https://ci.ros2.org/job/ci_linux/8259/)

Edit: re-triggered (same two test failures that exist on the `ros2` branch)

**Comment by chapulina** [comment]
Started a build using the current `ros2` branch so we have a basis for comparison: [Build Status](https://ci.ros2.org/job/ci_linux/8127/)

**Comment by jacobperron** [comment]
I was unable to reproduce all of the failures on `ros2` locally. Rebuilding `ros2` branch to check again: [Build Status](https://ci.ros2.org/job/ci_linux/8257/)

I can reproduce these two test failures locally.

**Comment by jacobperron** [comment]
I also ran CI for the Dashing branch [Build Status](https://ci.ros2.org/job/ci_linux/8258/)
The two test failures aren't there. The build failure is a job config error (I didn't build the metapackage, but colcon is trying to run tests for it).

**Comment by chapulina** [comment]
> I can reproduce these two test failures locally.

I think #974 hasn't been ported to `ros2` yet, which causes plugins like elevator and harness to fail. Could you check if that's the case? Thanks! :beach_umbrella:

**Comment by jacobperron** [comment]
> I think #974 hasn't been ported to ros2 yet, which causes plugins like elevator and harness to fail. Could you check if that's the case?

Thanks for the tip! Fixes the tests for me locally. Let's try again: [Build Status](https://ci.ros2.org/job/ci_linux/8274/)

**Comment by j-rivero** [comment]
Reviewing the changes between the `ros2` and `dashing` branches I was unable to find a missing commit. Good work Jacob, thanks for the PR.

**Pull request merged**
