### PR TITLE
[backport][ros2] make transient local reliable (#1033)

### PR DESCRIPTION
**Pull request by Karsten1987**
eloquent backport of #1033

### CODE REVIEW

**Comment by Karsten1987** [comment]
test failures seem unrelated to the fix and the newly introduced test ran successfully.

**Comment by chapulina** [comment]
Actually it looks like the new test is responsible for the test failures. It looks like `gzserver` didn't shut down properly at the end of the test:

```
11:32:38 19: [INFO] [gzserver-2]: sending signal 'SIGINT' to process[gzserver-2]
11:32:38 19: [INFO] [mock_robot_state_publisher-1]: sending signal 'SIGINT' to process[mock_robot_state_publisher-1]
11:32:38 19: [mock_robot_state_publisher-1] [INFO] [mock_robot_state_publisher]: Publishing on /mock_robot_description
11:32:38 19: [mock_robot_state_publisher-1] [INFO] [rclcpp]: signal_handler(signal_value=2)
11:32:38 19: [INFO] [mock_robot_state_publisher-1]: process has finished cleanly [pid 7382]
11:32:43 19: [ERROR] [gzserver-2]: process[gzserver-2] failed to terminate '5' seconds after receiving 'SIGINT', escalating to 'SIGTERM'
11:32:43 19: [INFO] [gzserver-2]: sending signal 'SIGTERM' to process[gzserver-2]
11:32:43 19: [ERROR] [gzserver-2]: process has died [pid 7383, exit code -15, cmd 'gzserver                                                                    -s libgazebo_ros_init.so   -s libgazebo_ros_factory.so       '].
```

Which makes all subsequent tests fail with

```
11:32:46 7: [1;31m[Err] [Master.cc:96] [0m[1;31mEXCEPTION: [0m[1;31mUnable to start server[bind: Address already in use]. There is probably another Gazebo process running.
11:32:46 7: [0m[1;31m
11:32:46 7: [0m[1;31m[0mterminate called after throwing an instance of 'gazebo::common::Exception'
```

Could be flaky, let's try again.

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
Same thing again. I wonder if it's somehow related to the CI infrastructure, since #1033 tested ok on ci.ros2.org.

I'm adding PR CI for `eloquent` to the OSRF farm so we have another point of reference: https://bitbucket.org/osrf/release-tools/pull-requests/945/

**Comment by chapulina** [comment]
@osrf-jenkins run tests please

**Comment by hidmic** [comment]
> It looks like `gzserver` didn't shut down properly at the end of the test:

Maybe 5 seconds isn't enough for Gazebo to shut down? It'd be a bit unfortunate, but you can try bumping up [SIGTERM and SIGKILL timeouts](https://github.com/ros2/launch/blob/4333910ba41977f3ab9867082c86a8698ada3a16/launch/launch/actions/execute_process.py#L96-L99).

**Comment by chapulina** [comment]
Thanks, @hidmic. A combination of the timeouts and #1037 worked locally for me: 36e9bd33b6f46bd05c5827e762ccad38aa4ea554

**Review by chapulina — APPROVED** [review]
Thanks for the endurance

**Pull request merged**
