### PR TITLE
gazebo_ros_openni_kinect plugin: adds publishing of the camera info again (fixes #95)

### LINKED ISSUE #95: gazebo_plugins: gazebo_ros_openni_kinect plugin not publishing depth and rgb camera info
I believe the important function to publish the camera info is

```
GazeboRosOpenniKinect::PublishCameraInfo()
```

However, I don't see anything calling it ever, which might be the cause of this issue.
For testing I have added a call of this function in `OnNewDepthFrame()`, but I am not sure this is the right place.

### PR DESCRIPTION
**Pull request by bit-pirate**

### CODE REVIEW

**Comment by davetcoleman** [comment]
Related to https://github.com/ros-simulation/gazebo_ros_pkgs/issues/95#issuecomment-22213533

**Comment by piyushk** [comment]
I've tested this and it works fine.

**Comment by davetcoleman** [comment]
Thanks!

**Comment by piyushk** [comment]
@davetcoleman @bit-pirate 

I am still seeing sporadic instances where gazebo_ros_openni_kinect does not publish depth information. Are either of you seeing something like this?

**Comment by bit-pirate** [comment]
I haven't seen any glitches so far, but I also haven't been testing the turtlebot simulation extensively yet.
Does the depth _camera_ info stream cause troubles or the depth stream itself?

**Comment by piyushk** [comment]
Both of them are missing. I can't reproduce the error right now, but I get
a synchronization error on repeat from image_transport stating that only 1
CameraInfo message received in the last 10 seconds and 0 Image messages.
However, rostopic echo produces nothing for both. The image stream and
camera info is fine.

**Comment by davetcoleman** [comment]
I'm afraid I haven't been using the openni_kinect plugin and do not have a test setup for this. Too many other projects on my plate...

**Comment by bit-pirate** [comment]
I'll try to test this as soon as possible, but I'm buried in other
things, too.

2013/8/22 Dave Coleman notifications@github.com

> I'm afraid I haven't been using the openni_kinect plugin and do not have a
> test setup for this. Too many other projects on my plate...
> 
> ## 
> 
> Reply to this email directly or view it on GitHubhttps://github.com/ros-simulation/gazebo_ros_pkgs/pull/97#issuecomment-23061755
> .

## 

Marcus Liebhardt
Adresse: Zimmer 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republik
Korea
Address: Room 403, 634-1 Seongsan-dong, Mapo-gu, 121-846, Seoul, Republic
of Korea
주소: 대한민국 서울특별시 121-846 마포구 634-1 성산동 4 층 403 호
Mobile / Mobilfunk: +82 10 3322 0566
Email: ich@marcusliebhardt.de ich@marcusliebhardt.de

**Comment by piyushk** [comment]
No worries. I don't think it's a crucial issue. I'll get back to it as time permits. In any case, I am unable to use gazebo_ros_openni_kinect in multi-robot experiments because of #99.

@bit-pirate If you get some time, could you take a look at https://github.com/ros-drivers/openni_launch/issues/5? I would like to solve openni_launch issues before beta finishes.

Thanks!!

**Pull request merged**
