### PR TITLE
Update maintainer for Kinetic release

### PR DESCRIPTION
**Pull request by j-rivero**
issue #425

### CODE REVIEW

**Comment by caguero** [comment]
You didn't update `gazebo_ros_control`, was that intentionally?

**Comment by j-rivero** [comment]
> You didn't update gazebo_ros_control, was that intentionally?

not really but it was not a bad idea :)

**Comment by wjwwood** [comment]
lgtm

**Comment by scpeters** [comment]
+1

**Comment by caguero** [comment]
+1

**Pull request merged**
