### PR TITLE
Update header license for indigo

### PR DESCRIPTION
**Pull request by hsu**

### CODE REVIEW

**Comment by meyerj** [comment]
Not sure why I was asked to approve it. Probably because of some older pull requests.
+1

**Comment by hsu** [comment]
@meyerj yes, you contributed to openni kinect and depth camera classes. Thanks!

**Comment by nkoenig** [comment]
+1

**Comment by jbohren** [comment]
+1 for hand-of-god and any other modifications in this PR

**Comment by davetcoleman** [comment]
+1 the old license always bothered me, thanks!

**Comment by scpeters** [comment]
Should this target the indigo-devel branch?

**Comment by scpeters** [comment]
+1 for file changes, though I think the target branch should be indigo-devel

**Comment by hsu** [comment]
@scpeters you're right, target should be indigo, the old target got merged already. Is there a way of changing pull request targets in github?

**Comment by scpeters** [comment]
I think it's not possible: https://github.com/isaacs/github/issues/18

The recommended approach is to create a new pull request and reference this one so people can still find the discussion.

**Comment by hsu** [comment]
closing to make a new pull request with indigo-devel as target

**Comment by hsu** [comment]
new pull request #237

**Pull request closed without merging**
