### PR TITLE
Add output arg to launch files, plus some small fixes (lunar)

### PR DESCRIPTION
**Pull request by MatthijsBurgh**
Simalar to #905

### CODE REVIEW

**Comment by chapulina** [comment]
It looks like the test failure in `Lpr...` is new, I haven't looked closely to find out if it could have been caused by this PR though

**Comment by MatthijsBurgh** [comment]
@chapulina As you can see in #910 and #911. (Separate PRs for both commits affecting `empty_world.launch`). In both PR, the `Lpr` is building and succeeding the test which failed in this PR. The test failed because of the time limit of 100 seconds.

I think running the CI again, would already fix it. Could you do this? Or are you convinced and by the other PRs?

**edit:** Figured out how to restart the CI.

**Comment by MatthijsBurgh** [comment]
@ros-pull-request-builder retest please

**Comment by MatthijsBurgh** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
Thanks for taking care of CI, merging!

**Pull request merged**
