### PR TITLE
spawn_model: adding -b option to bond to the model and delete it on sigint

### PR DESCRIPTION
**Pull request by jbohren**

### CODE REVIEW

**Comment by fmessmer** [comment]
Nice tiny feature...also works when cherry-picked on top of latest `indigo-devel`...

**Comment by hsu** [comment]
+1

can you add a working example launch file in [`gazebo_ros/test`](https://github.com/ros-simulation/gazebo_ros_pkgs/tree/hydro-devel/gazebo_ros/test)?

**Comment by jbohren** [comment]
Sorry, I don't think I'll have time to add a unit test, it's a pretty straightforward option.

**Comment by hsu** [comment]
No problem. Looks good, I'll merge after the conflict is resolved. Thanks.

**Comment by scpeters** [comment]
see #303

**Pull request closed without merging**
