### PR TITLE
remove travis in favor of build.ros.org PR testing

### PR DESCRIPTION
**Pull request by wjwwood**
@j-rivero @caguero FYI

### CODE REVIEW

**Comment by wjwwood** [comment]
I expect this to fail the first time (since we have missing dependencies in kinetic). I'll update after seeing it fail.

**Comment by jackieokay** [comment]
First build fails as expected

http://build.ros.org/job/Kpr__gazebo_ros_pkgs__ubuntu_xenial_amd64/1/

**Comment by wjwwood** [comment]
4f3c5a8 should ignore the `gazebo_ros_control` package.

**Comment by wjwwood** [comment]
We need https://github.com/ros-simulation/gazebo_ros_pkgs/pull/426 before this will pass @jacquelinekay is testing that pr with https://github.com/ros-simulation/gazebo_ros_pkgs/commit/4f3c5a8f4f7bbc3603a0b4da3abf2d9f5ad5efb3.

**Comment by j-rivero** [comment]
@ros-pull-request-builder test this please

**Comment by jackieokay** [comment]
+1

**Pull request merged**
