### PR TITLE
[backport] Backport multicamera to dashing

### PR DESCRIPTION
**Pull request by shiveshkhaitan**
Backport `gazebo_ros_multi_camera`, `gazebo_ros_triggered_multicamera` and `multi_camera_plugin` #939 to dashing

### CODE REVIEW

**Review by chapulina — APPROVED** [review]
Nice work! I fixed a typo on 488c747d05c0e3127bde232342766fef4e14da30 to fix the test. We probably need to port this to `ros2`.

Will merge when CI comes back happy.

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by shiveshkhaitan** [comment]
> I fixed a typo on 488c747 to fix the test.

Sorry about this. I think on rebuilding, previously installed worlds do not get removed. So when I tried building, using previously installed `gazebo_ros_multicamera.world`, the tests passed

> We probably need to port this to ros2

In `ros2`, the world name is `gazebo_ros_multicamera.world` and its consistent with the one loaded in test. Should I change both of them to `gazebo_ros_multi_camera.world`?

**Comment by chapulina** [comment]
> Should I change both of them to gazebo_ros_multi_camera.world?

Should be ok the way it is now.

**Pull request merged**
