### PR TITLE
Enabling continuous integration with Travis (jade)

### PR DESCRIPTION
**Pull request by j-rivero**
First part of integration with Travis.

Tests are failing although the build is marked as successful. The patches for the testing suite will become in a new pull request. We probably need X support to run the testing suite but at least we can integrate in Travis some static/dynamic analysis tools and it check the compilation with the ros of gazebo and ROS ecosystem.

A new pull request should be directed to the `indigo-devel` branch and new support will be added to test different versions of gazebo.

The testing result of travis in my fork: https://travis-ci.org/j-rivero/gazebo_ros_pkgs/builds/111649828.

Mental note: enable travis integration after merging in the travis console for this repo.

### CODE REVIEW

**Comment by carlosjoserg** [comment]
> Tests are failing although the build is marked as successful. 

Sounds like a [volkswagen](https://github.com/auchenberg/volkswagen) thing, you better start greppin `require('volkswagen')` ;)

The successful build would mean that the command `catkin run_tests -p1 -j4 --summary` successfully ran the test, found that tests are failing and reported so, and finally exits with 0...

This issue might help ros/catkin#576, they suggest to use `catkin_test_results`

**Comment by scpeters** [comment]
We have `catkin_test_results` in the robot_model travis file:
- https://github.com/ros/robot_model/blob/indigo-devel/.travis.yml

**Comment by j-rivero** [comment]
Thanks for the comments, it is failing now as expected.

**Comment by scpeters** [comment]
+1

**Pull request merged**
