### PR TITLE
Rename initial_parameters -> parameter_overrides.

### PR DESCRIPTION
**Pull request by clalancette**
Signed-off-by: Chris Lalancette <clalancette@openrobotics.org>

### CODE REVIEW

**Comment by clalancette** [comment]
@chapulina FYI, we may want to consider making a `dashing` branch and targeting this PR there.

**Comment by chapulina** [comment]
Thanks for the PR, I'm actually refactoring our usage of parameters a bit at the moment not to use `allow_undeclared_parameters`. I'll hopefully have a PR by end of day.

Currently `ros2` is the dashing branch. The idea is to branch off once there's a breaking change on E-turtle.

**Comment by dirk-thomas** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
https://github.com/ros-simulation/gazebo_ros_pkgs/pull/931 should have the complete fix for parameters.

**Comment by chapulina** [comment]
Thanks again, @clalancette . #931 has been merged.

**Pull request closed without merging**
