### PR TITLE
[ros2] Add support for the orientation_reference_frame SDF option for IMU sensors

### PR DESCRIPTION
**Pull request by jcmonteiro**
It is now possible to change the IMU reference frame instead of always acquiring data with respect to the initial IMU pose.

I wrote unit tests for all supported (based on the current SDF spec) use cases.

Besides, it looks like this feature should be added to the Gazebo IMU sensor class, but I found it easier and faster to do it here.

### CODE REVIEW

**Comment by chapulina** [comment]
Thanks for the PR!

[Here](https://bitbucket.org/osrf/gazebo/branches/compare/issue_1959_gazebo7%0Dgazebo7#chg-gazebo/sensors/ImuSensor.cc)'s an initial implementation for Gazebo and [here](https://bitbucket.org/osrf/gazebo/issues/1959)'s an issue tracking it.

As you mentioned, ideally this would be handled on the Gazebo side. And if this ever gets implemented there, some assumptions on this PR should be changed.

I'm curious to know why you "found it easier and faster to do it here."

Finally, note the test failures on CI, and check the [contribution guide](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-contribution-guide) for other tips.

**Comment by jcmonteiro** [comment]
> As you mentioned, ideally this would be handled on the Gazebo side. And if this ever gets implemented there, some assumptions on this PR should be changed.

I believe the changes added to this PR would become obsolete as soon as they implement them on the Gazebo side. I might submit them there if I have the time.

> I'm curious to know why you "found it easier and faster to do it here."

Mainly because recompiling Gazebo and installing it from source for everybody in my workplace is kind of a dealbreaker. Also, changes here tend to reach upstream really fast.

> Finally, note the test failures on CI, and check the [contribution guide](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-contribution-guide) for other tips.

My bad... I did solve these issues but forgot to force push them before making the pull request. I will do this tomorrow morning.

**Comment by chapulina** [comment]
> Mainly because recompiling Gazebo and installing it from source for everybody in my workplace is kind of a dealbreaker.

Thank you for the feedback, that's helpful. I think there's a misconception there though, because there wouldn't be a need to build from source. We periodically release minor versions of Gazebo 9 which they could use.

> Also, changes here tend to reach upstream really fast.

I think that's also a misconception. We did a recent push to port `gazebo_ros_pkgs` to ROS 2, but as most of the work is done, the level of maintenance of this package will be closer to that of Gazebo's. :wink: 

---

That all said, I'd really recommend you target this at Gazebo :grimacing:

**Comment by jcmonteiro** [comment]
I mean compile from source while the changes do not reach the upstream. But you're right, this feature should really be targeted at Gazebo.

I might have the time to do it in a couple of weeks. Should this PR be considered anyway (after I force push to fix the CI errors, naturally, and assuming all changes are in fact correct)?

**Comment by chapulina** [comment]
> Should this PR be considered anyway

How about waiting for it to get into Gazebo? Your team should be able to use your branch until then. My worry is that we'll need to come back and revert this once it's in Gazebo.

**Comment by jcmonteiro** [comment]
Agreed. Feel free to close the PR then. I'll implement the changes in Gazebo if I have the time.

**Comment by chapulina** [comment]
Thanks!

Closing as the changes will be ported to Gazebo.

**Pull request closed without merging**
