### PR TITLE
[forward port] Image publishers use SensorDataQoSProfile (#1031)

### PR DESCRIPTION
**Pull request by jacobperron**
This is a forward port of #1031 from Eloquent.

### CODE REVIEW

**Comment by chapulina** [comment]
Mind triggering CI as described in [the wiki](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-CI#next-turtle)?

**Comment by jacobperron** [comment]
Linux: [Build Status](https://ci.ros2.org/job/ci_linux/9505/)

**Comment by jacobperron** [comment]
For comparison, I've triggered jobs for `ros2` and `eloquent` branches:

* ros2 [Build Status](https://ci.ros2.org/job/ci_linux/9516/)
* eloquent  [Build Status](https://ci.ros2.org/job/ci_linux/9536/)

**Comment by chapulina** [comment]
Oh gosh, has uncrustify been updated? All these tests have been passing fine.

The `[Err] [Master.cc:96] EXCEPTION: Unable to start server[bind: Address already in use]. There is probably another Gazebo process running.` errors are concerning. This means some test is starting Gazebo but not being able to kill it.

**Comment by jacobperron** [comment]
> Oh gosh, has uncrustify been updated? All these tests have been passing fine.

I believe the uncrustify errors are due to https://github.com/ament/ament_lint/pull/210, which changed the default config file used for ROS 2.

Edit: The eloquent build I triggered is incorrect since it is using the latest ROS 2 branches. I'll retrigger it.

**Comment by jacobperron** [comment]
PR fixing uncrustify errors: https://github.com/ros-simulation/gazebo_ros_pkgs/pull/1060

**Comment by jacobperron** [comment]
I've rebased to resolve conflicts.

Linux: [Build Status](https://ci.ros2.org/job/ci_linux/9880/)

**Comment by chapulina** [comment]
This needs rebasing again

**Comment by jacobperron** [comment]
Rebased.
Linux: [Build Status](https://ci.ros2.org/job/ci_linux/11113/)

**Comment by chapulina** [comment]
uh oh `error: ‘SensorDataQos’ is not a member of ‘rclcpp’`

**Comment by jacobperron** [comment]
> uh oh error: ‘SensorDataQos’ is not a member of ‘rclcpp’

Fixed in 9791ebc :upside_down_face:

**Comment by jacobperron** [comment]
Linux: [Build Status](https://ci.ros2.org/job/ci_linux/11133/)

**Comment by jacobperron** [comment]
Rebased to get the latest fixes on `ros2`: [Build Status](https://ci.ros2.org/job/ci_linux/11191/)

**Review by chapulina — APPROVED** [review]

**Pull request merged**
