### PR TITLE
[ros2] Camera and triggered camera

### PR DESCRIPTION
**Pull request by chapulina**
See [ROS 2 Migration: Camera](https://github.com/ros-simulation/gazebo_ros_pkgs/wiki/ROS-2-Migration:-Camera).

This needs https://github.com/ros-perception/image_common/pull/95 .

TODOs:

* This PR uses features not available on Bouncy, so all CI will fail. FYI @j-rivero 

* I didn't have time to port dynamic reconfigure. I left the ROS1 code commented out. Feel free to implement it if you feel inspired or I can take it when I get back.

* The `gazebo_ros_camera_distortion` test fails on teardown because the ROS node's destructor hangs forever. Not sure yet if the problem is coming from `rclcpp`, `gazebo_ros` or `image_transport`.

---

## Demos

All instructions to run the demos can be found on their world files.

### gazebo_ros_camera_demo

gazebo_ros_camera_demo

### gazebo_ros_triggered_camera_demo

gazebo_ros_camera_triggered_demo

### gazebo_ros_camera_distortion_barrel_demo

gazebo_ros_camera_distortion_barrel_demo

### gazebo_ros_camera_distortion_pincushion_demo

gazebo_ros_camera_distortion_pincushion_demo

---

### CODE REVIEW

**Review by mjcarroll — APPROVED** [review]
Generally looks good to me. 

I'm interested to know why the `ros_node_.reset()` causes issues here.  May be worth adding an issue to track it if you haven't already.

**Comment by chapulina** [comment]
Thanks for the review, @mjcarroll ! I'll take another look at the node reset issue this week and ticket an issue if I can't make progress.

We should only merge this PR once we have CI working for it. I think this means we need:

- [x]  `image_transport` into [Crystal release](http://repo.ros2.org/status_page/ros_crystal_default.html)
- [x] `message_filters` into into [ros2.repos](https://github.com/ros2/ros2/blob/master/ros2.repos)
- [x] `camera_info_manager` into [Crystal release](http://repo.ros2.org/status_page/ros_crystal_default.html)
- [x] `cv_bridge` [Crystal release](http://repo.ros2.org/status_page/ros_crystal_default.html)
- [ ]  `ros2_gazebo_pkgs-ci-pr_any_bouncy-bionic-amd64` to use crystal instead of bouncy
- [ ] Disable `Bpr__gazebo_ros_pkgs__ubuntu_bionic_amd64` and use https://ci.ros2.org/ until we have crystal jobs.

**Comment by mjcarroll** [comment]
`message_filters`: https://github.com/ros2/ros2/pull/588

**Comment by chapulina** [comment]
[PR disabling the OSRF build farm for Bouncy](https://bitbucket.org/osrf/release-tools/pull-requests/677/disable-bouncy-jobs/diff)

**Comment by chapulina** [comment]
Updated this PR on da044a5 to use `image_transport`'s topic remapping: https://github.com/ros-perception/image_common/pull/97

**Comment by chapulina** [comment]
So after today's meeting, it was decided that this PR will wait until there are Crystal debs available, so we can use those on the OSRF buildfarm for CI. Until then, `gazebo_ros_pkgs`'s `ros2` branch should keep working against both Bouncy debs and the master `ros2.repos` built from source.

**Comment by chapulina** [comment]
Thanks @mjcarroll for handling the release of `image_common`. I just tested this branch against crystal debs and everything works fine :tada:

I'm trying to adapt the OSRF build farm CI to use crystal [here](https://bitbucket.org/osrf/release-tools/pull-requests/677). Will merge this and the other 2 PRs targeted at `ros2` before making the Crystal release.

**Comment by chapulina** [comment]
OSRF build farm CI: [Build Status](https://build.osrfoundation.org/job/ros2_gazebo_pkgs-ci-pr_any_crystal-bionic-amd64/3/)

* the sim time tests are also failing in the `ros2` branch
* not sure yet why the camera tests are failing in Jenkins, they pass for me locally
* not sure what's going on with uncrustify either

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by j-rivero** [comment]
@osrf-jenkins run tests please

**Comment by chapulina** [comment]
Not going to delay this further, merging now even though there's no CI to test it. All pass locally, we should revisit once we have GPU-enabled CI working.

**Pull request merged**
