### PR TITLE
[ros2] Revert sim time test

### PR DESCRIPTION
**Pull request by chapulina**
This needs https://github.com/ros2/rclcpp/pull/608

### CODE REVIEW

**Comment by chapulina** [comment]
Build including the rclcpp PR: [Build Status](https://ci.ros2.org/job/ci_linux/5876/)

**Comment by chapulina** [comment]
Ok, giving up on testing the combination with CI since lots of `gazebo_ros_pkgs` dependencies are not there, some are ignored.... We'll just build everything locally :grimacing:

**Comment by tfoote** [comment]
Reattempting CI with forked ci scripts for removing blacklisted msgs packages and still rclcpp PR: [Build Status](https://ci.ros2.org/job/ci_linux/5877/)

**Comment by chapulina** [comment]
@ros-pull-request-builder retest this please

**Comment by chapulina** [comment]
FYI @tfoote, the sim time test is passing with this branch now :wink:

**Review by j-rivero — APPROVED** [review]

**Pull request merged**
