### PR TITLE
Adds range plugin for infrared and ultrasound sensors from pal robotics

### PR DESCRIPTION
**Pull request by AlexReimann**
Pull request for #162 

Only tested if it works, I didn't even look at the source code.

All is contributed from pal robotics

### CODE REVIEW

**Comment by bmagyar** [comment]
Good job, however the install rule wasn't updated with the new library. This only works if you compile it and use it from devel space. Do you mind adding it to this PR?
I will make a new PR against indigo and jade as well with the changes.

**Comment by AlexReimann** [comment]
I added it to the install rule. thanks for doing the PR for indigo / jade!

**Comment by 130s** [comment]
We may want to close this since Hydro is EOL and https://github.com/ros-simulation/gazebo_ros_pkgs/pull/335 for Indigo is merged.

**Comment by scpeters** [comment]
hydro is EOL

**Pull request closed without merging**
